# Generated by Django 3.2.4 on 2021-06-06 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_str', models.CharField(max_length=60)),
                ('response_str', models.TextField()),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
